In [2]:
import numpy as np
import pandas as pd

In [6]:
ruta = 'Ciudades_Visitadas_Latinoamerica_2023.csv'
ciudades = pd.read_csv(ruta)
ciudades

              Ciudad       País  Población  Visitantes
0   Ciudad de México     México    9265833    21000000
1       Buenos Aires  Argentina    3059574    15000000
2     Río de Janeiro     Brasil    6748314    13000000
3               Lima       Perú    9756020     9000000
4             Bogotá   Colombia    7181663     8000000
5  Santiago de Chile      Chile    6199241     7500000
6          São Paulo     Brasil   12333146    20000000
7          La Habana       Cuba    2164182     4000000
8             Cancún     México     888124     5000000
9          Cartagena   Colombia    1036671     3000000

In [8]:
np.round(ciudades['Población'] / 1000, 2)

0     9265.83
1     3059.57
2     6748.31
3     9756.02
4     7181.66
5     6199.24
6    12333.15
7     2164.18
8      888.12
9     1036.67
Name: Población, dtype: float64

In [10]:
mi_array = np.array([1.2345, 2.3456, 3.4567, 4.5678])
np.round(mi_array, 1)

array([1.2, 2.3, 3.5, 4.6])

In [ ]:
import time
lista_grande = list(range(1, 1000001))
array_grande = np.array(lista_grande)

7.69 ms ± 145 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [13]:
inicio_lista = time.time()
for i in lista_grande:
    i_squared = i ** 2
fin_lista = time.time()
print("Tiempo con lista:", fin_lista - inicio_lista)

Tiempo con lista: 0.2503492832183838

In [19]:
array_grande = time.time()
array_squared = array_grande ** 2
fin_array = time.time()
print("Tiempo con array:", fin_array - array_grande)

Tiempo con array: 0.00011444091796875

In [29]:
array_enteros = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
array_enteros

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [30]:
primer_array_anidado = array_enteros[0]
primer_array_anidado

array([10, 20, 30])

In [25]:
primer_dato = array_enteros[0, 0]
primer_dato

np.int64(10)

In [26]:
quinto_dato = array_enteros[1, 2]
quinto_dato

np.int64(60)

In [31]:
# ahora aplicar slicing
fila_completa = array_enteros[1, :]
fila_completa

array([40, 50, 60])

In [32]:
# ahora aplicar slicing a columnas
columna_completa = array_enteros[:, 2]
columna_completa

array([30, 60, 90])

In [33]:
# ahora desde una posición intermedia
sub_array = array_enteros[0:2, 1:3]
sub_array

array([[20, 30],
       [50, 60]])

In [35]:
# ahora indexacion booleana
mask = array_enteros > 50
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [36]:
array_mayores_50 = array_enteros[mask]
array_mayores_50

array([60, 70, 80, 90])

In [38]:
array_numeros_hasta_10 = np.arange(1, 11)
array_numeros_hasta_10.shape

(10,)

In [40]:
array_con_reshape = array_numeros_hasta_10.reshape(2, 5)
array_con_reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
array_transpuesto = array_con_reshape.transpose()
array_transpuesto

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [42]:
# convertir un array en una dimensión
array_aplanado = array_con_reshape.flatten()
array_aplanado

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# el broadcasting permite operaciones entre arrays de diferentes formas
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([10, 20, 30])
array_suma = array_a + array_b # la suma se realiza elemento a elemento como ejemplo seria: 1+10, 2+20, 3+30, etc.
array_suma

array([[11, 22, 33],
       [14, 25, 36]])

## Limpiar Datos con Numpy

In [45]:
array_con_faltante = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
array_con_faltante

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [46]:
np.isnan(array_con_faltante)

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [47]:
# promedio ignorando los NaN
np.nanmean(array_con_faltante)

np.float64(5.285714285714286)

In [ ]:
# usar where para reemplazar valores NaN
array_sin_nan = np.where(np.isnan(array_con_faltante), 0, array_con_faltante) # funciona como un if de excelS
array_sin_nan

array([[1., 2., 0.],
       [4., 0., 6.],
       [7., 8., 9.]])

In [50]:
promedio_actualizado = np.mean(array_sin_nan)
promedio_actualizado

np.float64(4.111111111111111)

In [51]:
# Eliminar los datos faltantes
array_sin_nan_eliminado = array_con_faltante[~np.isnan(array_con_faltante)]
array_sin_nan_eliminado

array([1., 2., 4., 6., 7., 8., 9.])

In [57]:
# Importar y exportar datos con NumPy
np.savetxt('array_sin_nan.csv', array_sin_nan, delimiter=',')
# array_cargado = np.loadtxt('array_sin_nan.csv', delimiter=',')
array_cargado = np.genfromtxt('array_sin_nan.csv', delimiter=',', filling_values=0, dtype=float) # si hay NaN los rellena con 0
# array_cargado = np.genfromtxt('array_sin_nan.csv', delimiter=',', skip_header=0) # si hay cabecera la salta
array_cargado

array([[1., 2., 0.],
       [4., 0., 6.],
       [7., 8., 9.]])

## Trabajando con Numpy y Pandas

In [58]:
import pandas as pd

In [59]:
num_pares_imparres = pd.DataFrame({ "impares": [1, 3, 5, 7, 9], "pares": [2, 4, 6, 8, 10] })
num_pares_imparres

   impares  pares
0        1      2
1        3      4
2        5      6
3        7      8
4        9     10

In [ ]:
valores_array = num_pares_imparres.values
valores_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [62]:
valores_array2 = num_pares_imparres.to_numpy()
valores_array2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [63]:
np.sqrt(valores_array2)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712],
       [3.        , 3.16227766]])

In [64]:
np.max(valores_array)

np.int64(10)

In [65]:
df_desde_np = pd.DataFrame(valores_array, columns=['Impares', 'Pares'])
df_desde_np

   Impares  Pares
0        1      2
1        3      4
2        5      6
3        7      8
4        9     10

In [66]:
# mostrar las columans del DataFrame
df_desde_np.columns

Index(['Impares', 'Pares'], dtype='object')

In [67]:
# mostrar las filas del DataFrame
df_desde_np.index

RangeIndex(start=0, stop=5, step=1)

In [68]:
# renombrar el nombre de las filas
df_desde_np.index = ['A', 'B', 'C', 'D', 'E']
df_desde_np

   Impares  Pares
A        1      2
B        3      4
C        5      6
D        7      8
E        9     10